toolchain = 'arm-none-eabi'
c_flags = [
	'-Os',
	'-nostdlib',
	'-nostartfiles',
	'-ffunction-sections',
	'-fdata-sections',
	'-mthumb',
	'-mcpu=cortex-m7',
	'-mfloat-abi=hard',
	'-mfpu=fpv5-d16',
	'-ffreestanding',
]
ld_flags = [
	'-mthumb',
	'-mcpu=cortex-m7',
	'-mfloat-abi=hard',
	'-mfpu=fpv5-d16',
	'-lm',
	'-lc',
	'-lgcc',
	'-lnosys',
	'-nostdlib',
	'-nostartfiles',
	'-fdata-sections',
	'-ffunction-sections',
	'--specs=nano.specs',
	'--specs=nosys.specs',
	'-Wl,--gc-sections',
]
source = [
	'startup.c',
	'wdt.c',
	'eefc.c',
	'pmc.c',
	'systick.c',
	'exceptions.c',
	'pio.c',
	'usb.c',
	'qspi.c',
	'usb_descriptors.c',
	'hal/hid.c',
	'hal/spi.c',
	'hal/ticks.c',
]

[dependencies]
cmsis-5 = {}
tinyusb = { target = 'microchip/samx7x' }
