name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-uhid
          - 'stm32f1-generic -c rival310'
          - 'stm32f1-generic -c bluepill'
          - 'efm32gg12b-generic -c sltb009a'
          - 'sams70-generic -c big-sammy'
          - 'atmega32u4-generic -c octomouse'
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed python-pip ninja gcc arm-none-eabi-gcc arm-none-eabi-binutils arm-none-eabi-newlib avr-gcc avr-binutils avr-libc pkgconf readline git

    - name: Install ninja_syntax
      run: pip install ninja_syntax

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Container permissions
      run: git config --global --add safe.directory '*'

    - name: Configure
      run: ./configure.py ${{ matrix.target }}

    - name: Build
      run: ninja

  compile-oss-fuzz:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed python-pip ninja clang git

    - name: Install ninja_syntax
      run: pip install ninja_syntax tomli

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Container permissions
      run: git config --global --add safe.directory '*'

    - name: Configure
      run: ./configure-oss-fuzz.py

    - name: Build
      run: ninja
