name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed clang git python-pip

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
