name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed python-pip ninja gcc git

    - name: Install nox
      run: pip install nox

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: nox -s test

    - uses: codecov/codecov-action@v1
      if: ${{ always() }}

  fuzz:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
          - memory
          - undefined
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed python-pip ninja clang git

    - name: Install nox
      run: pip install nox

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run fuzzing session
      run: nox -s "fuzz(sanitizer='${{ matrix.sanitizer }}')"

    - name: Archive crashes
      uses: actions/upload-artifact@v2
      with:
        path: crash-*
